/**
 * This code was originally generated by v0 by Vercel.
 * Edited heavily.
 * @see https://v0.dev/t/fXIzRj1zIak
 */
import { CardContent, Card } from "@/components/ui/card";
import Image from "next/image";

export function MainPage() {
  return (
    <div className="bg-white">
      <main className="p-6 md:p-12">
        <div className="max-w-2xl mx-auto mt-8">
          <Card>
            <CardContent className="p-6">
              <div className="flex items-start">
                <Image
                  src="/eth.svg"
                  alt="Ethereum Logo"
                  width={42}
                  height={42}
                  priority
                />
                <div className="ml-4 align-middle">
                  <h2 className="text-2xl font-semibold mb-2">
                    Real World Ethereum
                  </h2>
                  <p className="text-gray-600">{"/ˌriːəl wɜːld ɪˈθɪəriəm/"}</p>
                </div>
              </div>
              <p className="text-gray-600 mt-4 text-lg italic">
                Ethereum applications and infrastructure focused on real-world,
                non-speculative usage.
              </p>
            </CardContent>
          </Card>
        </div>
        <div className="max-w-2xl mx-auto mt-8 text-md text-gray-500">
          <p className="mt-2">
            Real World Ethereum (RWE) is a community effort to build Ethereum
            applications and infrastructure specifically aimed at real-world
            utility unrelated to trading. This page collects public content
            related to the cause.
          </p>
          <p className="mt-2">
            To make changes to this page please submit a pull request to the{" "}
            <a
              className="text-blue-500 underline"
              href="https://github.com/Real-World-Ethereum/website"
              target="_blank"
            >
              Github repo
            </a>
            .
          </p>
        </div>
        <div className="max-w-2xl mx-auto mt-8 text-lg">
          <div className="grid grid-cols-2 gap-8 mt-8">
            <div>
              <h3 className="text-xl font-semibold mb-2">RWE Today</h3>
              <div>
                <a className="text-blue-500 underline" href="#">
                  Why is Tether on Tron so popular?
                </a>
                <p className="text-gray-600">Liam Horne, Dec 2023</p>
              </div>
              <div className="mt-4">
                <a className="text-blue-500 underline" href="#">
                  Cash → Chain Istanbul
                </a>
                <p className="text-gray-600">Daimo team, Dec 2023</p>
              </div>
            </div>
            <div>
              <h3 className="text-xl font-semibold mb-2">RWE Tomorrow</h3>
              <p className="text-gray-600">Coming soon!</p>
            </div>
          </div>
          <div className="mt-8">
            <h3 className="text-xl font-semibold mb-2">
              Real World Ethereum Event
            </h3>
            <p className="text-gray-600">
              We&apos;re hosting a small event in San Francisco in
              January. <a
              className="text-blue-500 underline"
              href="./event"
            >
              Learn more
            </a>.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
